from sqlalchemy import Column, Integer, String, DateTime, Float
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

class Bcartmag(Base):
    __tablename__ = 'bcartmag'

    oarti = Column(Integer, primary_key=True)
    csoci = Column(Integer)
    iarti = Column(String)
    carti = Column(String)
    tarti = Column(String)
    cunmi_dmaga = Column(Integer)
    ndeci_xunmi = Column(Integer)
    ccate_sscve = Column(String)
    caiva = Column(Float)
    bagev_sxiva = Column(Float)
    cstat_darti = Column(String)
    qlott_scomm = Column(Float)
    carti_seste = Column(String)
    ccate_sgesa = Column(String)
    ccate_scrta = Column(String)
    qscor_sminx = Column(Float)
    barti_seffe = Column(String)
    barti_sprot = Column(String)
    ctipo_darti = Column(String)
    ccate_scpac = Column(String)
    cnume_dcocg_a = Column(Integer)
    ncocg_dcntr_a = Column(Integer)
    ccate_scpve = Column(String)
    cnume_dcocg_v = Column(Integer)
    ncocg_dcntr_v = Column(Integer)
    ccate_sprov = Column(String)
    ccate_sscac = Column(String)
    odise = Column(String)
    oarti_xrfci = Column(String)
    oarti_xrfdb = Column(String)
    oarti_xrfdp = Column(String)
    oarti_xrife = Column(String)
    ctipo_dcoqu = Column(String)
    cunmi_speso = Column(Integer)
    qpeso = Column(Float)
    cunmi_svolu = Column(Integer)
    qvolu = Column(Float)
    tmate = Column(DateTime)
    ttrat = Column(DateTime)
    tfini = Column(DateTime)
    qpeso_sspec = Column(Float)
    qresa = Column(Float)
    ccate_stoll = Column(String)
    ccate_setic = Column(String)
    oarti_xsost = Column(String)
    oarti_xgrup = Column(String)
    binse_inweb = Column(String)
    tarti_swebx = Column(String)
    tarti_xrice = Column(String)
    busat_xvari = Column(String)
    oarti_xvari_r = Column(String)
